
import { BuildingType, BuildingDef, StatType, BuildingCategory } from './types';

export const GRID_SIZE = 25; 
export const TICK_RATE_MS = 1000;
export const WINNING_SCORE = 100;
export const DAY_LENGTH_TICKS = 300; // 5 minutes per day

export const STAT_MULT = 0.001; 
const MONEY_MULT = 0.8;

export const BUILDINGS: Record<BuildingType, BuildingDef> = {
  [BuildingType.NONE]: {
    type: BuildingType.NONE,
    name: "Vide",
    description: "",
    category: BuildingCategory.NATURE,
    cost: 0,
    energyConsumption: 0,
    effects: {},
    color: "#000000", 
    scale: [0,0,0],
    size: [1, 1]
  },
  [BuildingType.BULLDOZER]: {
    type: BuildingType.BULLDOZER,
    name: "Bulldozer",
    description: "Détruit les bâtiments (50% remboursé).",
    category: BuildingCategory.TOOLS,
    cost: 0,
    energyConsumption: 0,
    effects: {},
    color: "#ff0000",
    scale: [1, 1, 1],
    size: [1, 1]
  },

  // --- ENERGY ---
  [BuildingType.SOLAR_PANEL_SMALL]: {
    type: BuildingType.SOLAR_PANEL_SMALL,
    name: "Panneau Solaire (S)",
    description: "Énergie propre. Inactif la nuit.",
    category: BuildingCategory.ENERGY,
    cost: 50,
    energyConsumption: 5,
    isSolar: true,
    effects: {},
    color: "#4287f5",
    scale: [0.8, 0.1, 0.8],
    size: [1, 1]
  },
  [BuildingType.SOLAR_PANEL_LARGE]: {
    type: BuildingType.SOLAR_PANEL_LARGE,
    name: "Ferme Solaire",
    description: "Grosse production de jour.",
    category: BuildingCategory.ENERGY,
    cost: 200,
    energyConsumption: 25,
    isSolar: true,
    effects: {},
    color: "#2266cc",
    scale: [1.5, 0.1, 1.5],
    size: [2, 2]
  },
  [BuildingType.SOLAR_ORBITAL_UPLINK]: {
    type: BuildingType.SOLAR_ORBITAL_UPLINK,
    name: "Liaison Orbitale",
    description: "Capte l'énergie solaire 24/7 depuis l'espace.",
    category: BuildingCategory.ENERGY,
    cost: 2000,
    energyConsumption: 150,
    effects: {},
    color: "#00ffff",
    scale: [1.2, 3, 1.2],
    size: [2, 2]
  },
  [BuildingType.WIND_TURBINE]: {
    type: BuildingType.WIND_TURBINE,
    name: "Éolienne",
    description: "Production selon le vent.",
    category: BuildingCategory.ENERGY,
    cost: 150,
    energyConsumption: 15,
    minStats: { [StatType.WIND]: 10 },
    statScaling: { [StatType.WIND]: 0.01 }, 
    effects: { [StatType.WIND]: 0.5 * STAT_MULT },
    color: "#ffffff",
    scale: [0.4, 2, 0.4],
    size: [1, 1]
  },
  [BuildingType.WIND_TURBINE_OFFSHORE]: {
    type: BuildingType.WIND_TURBINE_OFFSHORE,
    name: "Éolienne Offshore",
    description: "Haute performance éolienne.",
    category: BuildingCategory.ENERGY,
    cost: 450,
    energyConsumption: 40,
    minStats: { [StatType.WIND]: 25 },
    statScaling: { [StatType.WIND]: 0.02 },
    effects: { [StatType.WIND]: 1 * STAT_MULT },
    color: "#e0e0e0",
    scale: [0.5, 2.5, 0.5],
    size: [1, 1]
  },
  [BuildingType.COAL_PLANT]: {
    type: BuildingType.COAL_PLANT,
    name: "Centrale Charbon",
    description: "Polluant mais fiable.",
    category: BuildingCategory.ENERGY,
    cost: 300,
    energyConsumption: 80,
    workersRequired: 10,
    effects: { [StatType.AIR]: -10 * STAT_MULT, [StatType.GREENERY]: -2 * STAT_MULT },
    pollutionRadius: 3,
    pollutionAmount: 4,
    color: "#333333",
    scale: [1.2, 1.5, 1.2],
    size: [2, 2]
  },
  [BuildingType.GAS_PLANT]: {
    type: BuildingType.GAS_PLANT,
    name: "Centrale Gaz",
    description: "Intermédiaire.",
    category: BuildingCategory.ENERGY,
    cost: 500,
    energyConsumption: 100,
    workersRequired: 15,
    effects: { [StatType.AIR]: -5 * STAT_MULT },
    pollutionRadius: 2,
    pollutionAmount: 2,
    color: "#554433",
    scale: [1.2, 1.2, 1.2],
    size: [2, 2]
  },
  [BuildingType.GEOTHERMAL_PLANT]: {
    type: BuildingType.GEOTHERMAL_PLANT,
    name: "Centrale Géothermique",
    description: "Énergie de la terre.",
    category: BuildingCategory.ENERGY,
    cost: 1200,
    energyConsumption: 120,
    minStats: { [StatType.EARTH]: 20 },
    effects: { [StatType.EARTH]: -0.5 * STAT_MULT },
    color: "#8b4513",
    scale: [1.5, 0.8, 1.5],
    size: [2, 2]
  },
  [BuildingType.HYDRO_DAM]: {
    type: BuildingType.HYDRO_DAM,
    name: "Barrage Hydro",
    description: "Utilise l'eau et la verdure.",
    category: BuildingCategory.ENERGY,
    cost: 1500,
    energyConsumption: 180,
    minStats: { [StatType.GREENERY]: 30 },
    effects: { [StatType.EARTH]: 1 * STAT_MULT, [StatType.GREENERY]: 1 * STAT_MULT },
    color: "#4682b4",
    scale: [2, 1, 1],
    size: [2, 1]
  },
  [BuildingType.BIOMASS_BURNER]: {
    type: BuildingType.BIOMASS_BURNER,
    name: "Brûleur Biomasse",
    description: "Convertit la nature en énergie.",
    category: BuildingCategory.ENERGY,
    cost: 600,
    energyConsumption: 60,
    minStats: { [StatType.GREENERY]: 10 },
    effects: { [StatType.GREENERY]: -5 * STAT_MULT, [StatType.AIR]: -2 * STAT_MULT },
    color: "#556b2f",
    scale: [1, 1.5, 1],
    size: [1, 1]
  },
  [BuildingType.NUCLEAR_PLANT]: {
    type: BuildingType.NUCLEAR_PLANT,
    name: "Centrale Nucléaire",
    description: "Puissant, besoin d'eau de refroidissement.",
    category: BuildingCategory.ENERGY,
    cost: 2500,
    energyConsumption: 400,
    workersRequired: 50,
    minStats: { [StatType.GREENERY]: 40 },
    effects: { [StatType.EARTH]: -2 * STAT_MULT, [StatType.GREENERY]: -1 * STAT_MULT },
    pollutionRadius: 1,
    pollutionAmount: 0.5,
    color: "#5577aa",
    scale: [1.8, 2, 1.8],
    size: [2, 2]
  },
  [BuildingType.FUSION_REACTOR]: {
    type: BuildingType.FUSION_REACTOR,
    name: "Réacteur Fusion",
    description: "Technologie propre et massive.",
    category: BuildingCategory.ENERGY,
    cost: 8000,
    energyConsumption: 1500,
    workersRequired: 100,
    minStats: { [StatType.AIR]: 50 },
    effects: { [StatType.AIR]: 1 * STAT_MULT },
    color: "#aa00ff",
    scale: [2, 2, 2],
    size: [2, 2]
  },
  [BuildingType.ANTIMATTER_REACTOR]: {
    type: BuildingType.ANTIMATTER_REACTOR,
    name: "Réacteur Antimatière",
    description: "L'ultime source d'énergie.",
    category: BuildingCategory.ENERGY,
    cost: 25000,
    energyConsumption: 5000,
    workersRequired: 500,
    minStats: { [StatType.AIR]: 70, [StatType.GREENERY]: 70, [StatType.WIND]: 70, [StatType.EARTH]: 70 },
    pollutionRadius: 5,
    pollutionAmount: 5, 
    effects: { [StatType.AIR]: -5 * STAT_MULT, [StatType.GREENERY]: -5 * STAT_MULT }, 
    color: "#000000",
    scale: [2.5, 3, 2.5],
    size: [3, 3]
  },

  // --- INDUSTRY ---
  [BuildingType.MINE_IRON]: {
    type: BuildingType.MINE_IRON,
    name: "Mine de Fer",
    description: "Extraction basique.",
    category: BuildingCategory.INDUSTRY,
    cost: 100,
    energyConsumption: -10,
    workersRequired: 5,
    resourceGeneration: 4 * MONEY_MULT,
    effects: { [StatType.EARTH]: -2 * STAT_MULT },
    pollutionRadius: 1,
    pollutionAmount: 1,
    color: "#8b4513",
    scale: [1, 0.5, 1],
    size: [1, 1]
  },
  [BuildingType.MINE_SILICON]: {
    type: BuildingType.MINE_SILICON,
    name: "Mine de Silicium",
    description: "Extraction technologique.",
    category: BuildingCategory.INDUSTRY,
    cost: 350,
    energyConsumption: -20,
    workersRequired: 10,
    minStats: { [StatType.EARTH]: 10 },
    resourceGeneration: 8 * MONEY_MULT,
    effects: { [StatType.EARTH]: -3 * STAT_MULT },
    pollutionRadius: 2,
    pollutionAmount: 1.5,
    color: "#a0522d",
    scale: [1.2, 0.6, 1.2],
    size: [1, 1]
  },
  [BuildingType.MINE_GOLD]: {
    type: BuildingType.MINE_GOLD,
    name: "Mine d'Or",
    description: "Richesse rapide.",
    category: BuildingCategory.INDUSTRY,
    cost: 1000,
    energyConsumption: -40,
    workersRequired: 20,
    resourceGeneration: 25 * MONEY_MULT,
    effects: { [StatType.EARTH]: -5 * STAT_MULT },
    color: "#ffd700",
    scale: [1.1, 0.5, 1.1],
    size: [1, 1]
  },
  [BuildingType.MINE_LITHIUM]: {
    type: BuildingType.MINE_LITHIUM,
    name: "Mine de Lithium",
    description: "Pour batteries.",
    category: BuildingCategory.INDUSTRY,
    cost: 1500,
    energyConsumption: -50,
    workersRequired: 25,
    resourceGeneration: 35 * MONEY_MULT,
    effects: { [StatType.GREENERY]: -4 * STAT_MULT, [StatType.EARTH]: -2 * STAT_MULT },
    color: "#e6e6fa",
    scale: [1.5, 0.4, 1.5],
    size: [1, 1]
  },
  [BuildingType.MINE_URANIUM]: {
    type: BuildingType.MINE_URANIUM,
    name: "Mine Uranium",
    description: "Matériau radioactif.",
    category: BuildingCategory.INDUSTRY,
    cost: 3000,
    energyConsumption: -100,
    workersRequired: 50,
    minStats: { [StatType.EARTH]: 40 },
    resourceGeneration: 60 * MONEY_MULT,
    effects: { [StatType.EARTH]: -8 * STAT_MULT, [StatType.GREENERY]: -5 * STAT_MULT },
    pollutionRadius: 4,
    pollutionAmount: 3,
    color: "#32cd32",
    scale: [1.3, 0.8, 1.3],
    size: [1, 1]
  },
  [BuildingType.FACTORY_SMALL]: {
    type: BuildingType.FACTORY_SMALL,
    name: "Petite Usine",
    description: "Manufacture standard.",
    category: BuildingCategory.INDUSTRY,
    cost: 600,
    energyConsumption: -30,
    workersRequired: 30,
    resourceGeneration: 15 * MONEY_MULT,
    effects: { [StatType.AIR]: -3 * STAT_MULT },
    pollutionRadius: 2,
    pollutionAmount: 1,
    color: "#666666",
    scale: [1, 1.2, 1],
    size: [1, 1]
  },
  [BuildingType.FACTORY_LARGE]: {
    type: BuildingType.FACTORY_LARGE,
    name: "Grande Usine",
    description: "Production de masse.",
    category: BuildingCategory.INDUSTRY,
    cost: 1800,
    energyConsumption: -80,
    workersRequired: 100,
    resourceGeneration: 50 * MONEY_MULT,
    effects: { [StatType.AIR]: -8 * STAT_MULT },
    pollutionRadius: 4,
    pollutionAmount: 3,
    color: "#444444",
    scale: [1.8, 1.5, 1.8],
    size: [2, 2]
  },
  [BuildingType.FACTORY_CHIP]: {
    type: BuildingType.FACTORY_CHIP,
    name: "Fonderie Puces",
    description: "Haute technologie.",
    category: BuildingCategory.INDUSTRY,
    cost: 5000,
    energyConsumption: -200,
    workersRequired: 150,
    minStats: { [StatType.AIR]: 30 },
    resourceGeneration: 120 * MONEY_MULT,
    effects: { [StatType.EARTH]: -2 * STAT_MULT, [StatType.AIR]: -1 * STAT_MULT },
    pollutionRadius: 2,
    pollutionAmount: 1,
    color: "#1e90ff",
    scale: [2, 1, 2],
    size: [2, 1]
  },
  [BuildingType.FACTORY_AEROSPACE]: {
    type: BuildingType.FACTORY_AEROSPACE,
    name: "Usine Aérospatiale",
    description: "Construction spatiale.",
    category: BuildingCategory.INDUSTRY,
    cost: 10000,
    energyConsumption: -400,
    workersRequired: 300,
    minStats: { [StatType.WIND]: 40 },
    resourceGeneration: 250 * MONEY_MULT,
    effects: { [StatType.AIR]: -5 * STAT_MULT, [StatType.WIND]: -2 * STAT_MULT },
    color: "#f0f8ff",
    scale: [3, 1.5, 3],
    size: [3, 3]
  },
  [BuildingType.RECYCLING_CENTER]: {
    type: BuildingType.RECYCLING_CENTER,
    name: "Centre Recyclage",
    description: "Transforme déchets en valeur.",
    category: BuildingCategory.INDUSTRY,
    cost: 800,
    energyConsumption: -20,
    workersRequired: 20,
    resourceGeneration: 10 * MONEY_MULT,
    effects: { [StatType.EARTH]: 5 * STAT_MULT },
    color: "#228b22",
    scale: [1.2, 1, 1.2],
    size: [2, 1]
  },

  // --- CIVIC ---
  [BuildingType.BANK]: {
    type: BuildingType.BANK,
    name: "Banque Centrale",
    description: "Gestion financière.",
    category: BuildingCategory.CIVIC,
    cost: 5000,
    energyConsumption: -50,
    workersRequired: 50,
    resourceGeneration: 100 * MONEY_MULT,
    effects: {},
    color: "#ffd700",
    scale: [1.5, 2, 1.5],
    size: [2, 2]
  },
  [BuildingType.DATA_CENTER]: {
    type: BuildingType.DATA_CENTER,
    name: "Data Center",
    description: "Infrastructure numérique.",
    category: BuildingCategory.CIVIC,
    cost: 3000,
    energyConsumption: -300,
    workersRequired: 20,
    minStats: { [StatType.WIND]: 20 },
    resourceGeneration: 80 * MONEY_MULT,
    effects: { [StatType.EARTH]: -1 * STAT_MULT },
    color: "#111111",
    scale: [2, 0.8, 2],
    size: [2, 1]
  },
  [BuildingType.HOSPITAL]: {
    type: BuildingType.HOSPITAL,
    name: "Hôpital",
    description: "Soins et santé.",
    category: BuildingCategory.CIVIC,
    cost: 2000,
    energyConsumption: -100,
    workersRequired: 100,
    effects: { [StatType.GREENERY]: 3 * STAT_MULT },
    resourceGeneration: 0,
    color: "#ff9999",
    scale: [1.5, 1.5, 1.5],
    size: [2, 2]
  },

  // --- LIVING ---
  [BuildingType.TENT]: {
    type: BuildingType.TENT,
    name: "Tente",
    description: "Abri temporaire.",
    category: BuildingCategory.LIVING,
    cost: 20,
    energyConsumption: 0,
    workersProvided: 2,
    resourceGeneration: 0.1 * MONEY_MULT,
    effects: {},
    color: "#d2b48c",
    scale: [0.5, 0.3, 0.5],
    size: [1, 1]
  },
  [BuildingType.SHACK]: {
    type: BuildingType.SHACK,
    name: "Cabane",
    description: "Logement basique.",
    category: BuildingCategory.LIVING,
    cost: 50,
    energyConsumption: -1,
    workersProvided: 5,
    waterConsumption: 1,
    resourceGeneration: 0.5 * MONEY_MULT,
    effects: {},
    color: "#8b4513",
    scale: [0.6, 0.5, 0.6],
    size: [1, 1]
  },
  [BuildingType.HOUSE]: {
    type: BuildingType.HOUSE,
    name: "Maison",
    description: "Logement familial.",
    category: BuildingCategory.LIVING,
    cost: 250,
    energyConsumption: -5,
    workersProvided: 10,
    waterConsumption: 2,
    resourceGeneration: 2 * MONEY_MULT,
    effects: {},
    color: "#e0e0e0",
    scale: [0.7, 0.6, 0.7],
    size: [1, 1]
  },
  [BuildingType.DUPLEX]: {
    type: BuildingType.DUPLEX,
    name: "Duplex",
    description: "Pour deux familles.",
    category: BuildingCategory.LIVING,
    cost: 450,
    energyConsumption: -8,
    workersProvided: 20,
    waterConsumption: 4,
    resourceGeneration: 5 * MONEY_MULT,
    effects: {},
    color: "#d3d3d3",
    scale: [0.9, 0.8, 0.8],
    size: [1, 1]
  },
  [BuildingType.APARTMENT]: {
    type: BuildingType.APARTMENT,
    name: "Immeuble",
    description: "Forte densité.",
    category: BuildingCategory.LIVING,
    cost: 1000,
    energyConsumption: -20,
    workersProvided: 50,
    waterConsumption: 10,
    resourceGeneration: 15 * MONEY_MULT,
    effects: { [StatType.AIR]: -1 * STAT_MULT },
    color: "#c0c0c0",
    scale: [1, 2, 1],
    size: [1, 1]
  },
  [BuildingType.CONDO_COMPLEX]: {
    type: BuildingType.CONDO_COMPLEX,
    name: "Résidence Luxueuse",
    description: "Haut standing.",
    category: BuildingCategory.LIVING,
    cost: 2500,
    energyConsumption: -40,
    workersProvided: 80,
    waterConsumption: 20,
    resourceGeneration: 40 * MONEY_MULT,
    effects: { [StatType.AIR]: -2 * STAT_MULT },
    color: "#f5f5dc",
    scale: [1.5, 1.5, 1.5],
    size: [2, 2]
  },
  [BuildingType.SKYSCRAPER]: {
    type: BuildingType.SKYSCRAPER,
    name: "Gratte-ciel",
    description: "Densité urbaine extrême.",
    category: BuildingCategory.LIVING,
    cost: 5000,
    energyConsumption: -100,
    workersProvided: 200,
    waterConsumption: 50,
    resourceGeneration: 100 * MONEY_MULT,
    effects: { [StatType.WIND]: -5 * STAT_MULT, [StatType.AIR]: -4 * STAT_MULT },
    pollutionRadius: 2,
    pollutionAmount: 1,
    color: "#aaddff",
    scale: [1.2, 4, 1.2],
    size: [1, 1]
  },
  [BuildingType.ARCOLOGY]: {
    type: BuildingType.ARCOLOGY,
    name: "Arcologie",
    description: "Ville utopique autonome.",
    category: BuildingCategory.LIVING,
    cost: 15000,
    energyConsumption: -500,
    workersProvided: 1000,
    waterConsumption: 100,
    minStats: { [StatType.AIR]: 50, [StatType.GREENERY]: 50 },
    resourceGeneration: 300 * MONEY_MULT,
    effects: { [StatType.GREENERY]: 5 * STAT_MULT, [StatType.AIR]: 2 * STAT_MULT }, 
    color: "#ffffff",
    scale: [2.5, 5, 2.5],
    size: [3, 3]
  },
  [BuildingType.ROBOT_HIVE]: {
    type: BuildingType.ROBOT_HIVE,
    name: "Ruche Robotique",
    description: "Robots infatigables.",
    category: BuildingCategory.LIVING,
    cost: 12000,
    energyConsumption: -800, // Huge energy drain
    workersProvided: 300, // Pure efficient workforce
    isRobot: true,
    resourceGeneration: 0,
    effects: { [StatType.AIR]: -1 * STAT_MULT }, // Heat/Production
    color: "#111111",
    scale: [2, 1.5, 2],
    size: [2, 2]
  },
  [BuildingType.MALL]: {
    type: BuildingType.MALL,
    name: "Centre Commercial",
    description: "Zone de consommation.",
    category: BuildingCategory.LIVING,
    cost: 4000,
    energyConsumption: -100,
    workersProvided: 20, 
    resourceGeneration: 150 * MONEY_MULT,
    effects: { [StatType.AIR]: -3 * STAT_MULT },
    pollutionRadius: 2,
    pollutionAmount: 2,
    color: "#ff69b4",
    scale: [2, 1, 2],
    size: [2, 2]
  },

  // --- NATURE ---
  [BuildingType.SMALL_TREE]: {
    type: BuildingType.SMALL_TREE,
    name: "Arbuste",
    description: "Plante décorative.",
    category: BuildingCategory.NATURE,
    cost: 20,
    energyConsumption: 0,
    effects: { [StatType.GREENERY]: 1 * STAT_MULT, [StatType.AIR]: 0.5 * STAT_MULT },
    color: "#2dba4e",
    scale: [0.3, 0.5, 0.3],
    size: [1, 1]
  },
  [BuildingType.LARGE_TREE]: {
    type: BuildingType.LARGE_TREE,
    name: "Grand Arbre",
    description: "Absorbe CO2.",
    category: BuildingCategory.NATURE,
    cost: 80,
    energyConsumption: 0,
    effects: { [StatType.GREENERY]: 3 * STAT_MULT, [StatType.AIR]: 2 * STAT_MULT },
    color: "#006400",
    scale: [0.5, 1.2, 0.5],
    size: [1, 1]
  },
  [BuildingType.FOREST_GROVE]: {
    type: BuildingType.FOREST_GROVE,
    name: "Bosquet",
    description: "Mini forêt.",
    category: BuildingCategory.NATURE,
    cost: 300,
    energyConsumption: 0,
    effects: { [StatType.GREENERY]: 8 * STAT_MULT, [StatType.AIR]: 5 * STAT_MULT },
    color: "#004d00",
    scale: [0.9, 1.5, 0.9],
    size: [1, 1]
  },
  [BuildingType.RAIN_COLLECTOR]: {
    type: BuildingType.RAIN_COLLECTOR,
    name: "Collecteur Pluie",
    description: "Récolte l'eau quand il pleut.",
    category: BuildingCategory.NATURE,
    cost: 400,
    energyConsumption: 0,
    waterGeneration: 10, // Active only during rain
    waterStorage: 50,
    effects: {},
    color: "#4fc3f7",
    scale: [0.8, 0.5, 0.8],
    size: [1, 1]
  },
  [BuildingType.WATER_TANK]: {
    type: BuildingType.WATER_TANK,
    name: "Château d'eau",
    description: "Stocke l'eau.",
    category: BuildingCategory.NATURE,
    cost: 800,
    energyConsumption: -2,
    waterStorage: 200,
    effects: {},
    color: "#336699",
    scale: [0.8, 1.5, 0.8],
    size: [1, 1]
  },
  [BuildingType.PARK]: {
    type: BuildingType.PARK,
    name: "Parc Public",
    description: "Espace détente.",
    category: BuildingCategory.NATURE,
    cost: 500,
    energyConsumption: -2,
    workersRequired: 2,
    effects: { [StatType.GREENERY]: 10 * STAT_MULT, [StatType.AIR]: 4 * STAT_MULT },
    resourceGeneration: 2 * MONEY_MULT,
    color: "#90ee90",
    scale: [0.9, 0.1, 0.9],
    size: [2, 2]
  },
  [BuildingType.LAKE]: {
    type: BuildingType.LAKE,
    name: "Lac",
    description: "Réserve d'eau naturelle.",
    category: BuildingCategory.NATURE,
    cost: 1000,
    energyConsumption: -5,
    waterStorage: 500,
    effects: { [StatType.GREENERY]: 15 * STAT_MULT, [StatType.EARTH]: 5 * STAT_MULT },
    color: "#00bfff",
    scale: [1, 0.05, 1],
    size: [2, 2]
  },
  [BuildingType.ALGAE_FARM]: {
    type: BuildingType.ALGAE_FARM,
    name: "Ferme Algues",
    description: "Conversion biologique.",
    category: BuildingCategory.NATURE,
    cost: 1200,
    energyConsumption: -15,
    minStats: { [StatType.GREENERY]: 20 },
    effects: { [StatType.AIR]: 20 * STAT_MULT, [StatType.GREENERY]: 10 * STAT_MULT },
    color: "#20b2aa",
    scale: [1.2, 0.5, 1.2],
    size: [2, 2]
  },
  [BuildingType.CORAL_REEF]: {
    type: BuildingType.CORAL_REEF,
    name: "Récif Corallien",
    description: "Écosystème marin.",
    category: BuildingCategory.NATURE,
    cost: 2500,
    energyConsumption: -10,
    minStats: { [StatType.GREENERY]: 50 },
    effects: { [StatType.GREENERY]: 25 * STAT_MULT, [StatType.AIR]: 15 * STAT_MULT },
    color: "#ff7f50",
    scale: [1, 0.2, 1],
    size: [2, 2]
  },

  // --- TERRAFORM ---
  [BuildingType.AIR_FILTER]: {
    type: BuildingType.AIR_FILTER,
    name: "Filtre Air",
    description: "Nettoyage atmosphérique.",
    category: BuildingCategory.TERRAFORM,
    cost: 500,
    energyConsumption: -20,
    effects: { [StatType.AIR]: 10 * STAT_MULT },
    color: "#e0ffff",
    scale: [0.8, 2, 0.8],
    size: [1, 1]
  },
  [BuildingType.CO2_SCRUBBER]: {
    type: BuildingType.CO2_SCRUBBER,
    name: "Épurateur CO2",
    description: "Capture carbone intense.",
    category: BuildingCategory.TERRAFORM,
    cost: 1200,
    energyConsumption: -60,
    effects: { [StatType.AIR]: 25 * STAT_MULT },
    color: "#708090",
    scale: [1, 2.5, 1],
    size: [2, 2]
  },
  [BuildingType.CLOUD_SEEDER]: {
    type: BuildingType.CLOUD_SEEDER,
    name: "Ensemenceur",
    description: "Favorise la pluie.",
    category: BuildingCategory.TERRAFORM,
    cost: 1500,
    energyConsumption: -50,
    effects: { [StatType.GREENERY]: 10 * STAT_MULT, [StatType.WIND]: 5 * STAT_MULT },
    color: "#f0f8ff",
    scale: [1, 3, 1],
    size: [2, 2]
  },
  [BuildingType.OZONE_GENERATOR]: {
    type: BuildingType.OZONE_GENERATOR,
    name: "Générateur Ozone",
    description: "Protection UV.",
    category: BuildingCategory.TERRAFORM,
    cost: 3000,
    energyConsumption: -100,
    minStats: { [StatType.AIR]: 30 },
    effects: { [StatType.AIR]: 40 * STAT_MULT, [StatType.EARTH]: 10 * STAT_MULT },
    color: "#7b68ee",
    scale: [1.5, 2.5, 1.5],
    size: [2, 2]
  },
  [BuildingType.CORE_DRILL]: {
    type: BuildingType.CORE_DRILL,
    name: "Foreuse Noyau",
    description: "Accès au magma.",
    category: BuildingCategory.TERRAFORM,
    cost: 5000,
    energyConsumption: -200,
    effects: { [StatType.EARTH]: 50 * STAT_MULT, [StatType.WIND]: 10 * STAT_MULT },
    pollutionRadius: 2,
    pollutionAmount: 0.5,
    color: "#8b0000",
    scale: [2, 3, 2],
    size: [2, 2]
  },
  [BuildingType.TECTONIC_STABILIZER]: {
    type: BuildingType.TECTONIC_STABILIZER,
    name: "Stabilisateur",
    description: "Sécurité sismique.",
    category: BuildingCategory.TERRAFORM,
    cost: 8000,
    energyConsumption: -300,
    minStats: { [StatType.EARTH]: 50 },
    effects: { [StatType.EARTH]: 80 * STAT_MULT },
    color: "#8b4500",
    scale: [3, 1, 3],
    size: [3, 3]
  },
  [BuildingType.WEATHER_STATION]: {
    type: BuildingType.WEATHER_STATION,
    name: "Station Météo",
    description: "Contrôle climatique.",
    category: BuildingCategory.TERRAFORM,
    cost: 2000,
    energyConsumption: -40,
    effects: { [StatType.WIND]: 20 * STAT_MULT },
    color: "#b0c4de",
    scale: [0.5, 4, 0.5],
    size: [1, 1]
  },

  // --- DEPOLLUTION ---
  [BuildingType.DEPOLLUTION_NODE_SMALL]: {
    type: BuildingType.DEPOLLUTION_NODE_SMALL,
    name: "Purificateur (S)",
    description: "Bloque la pollution locale.",
    category: BuildingCategory.TERRAFORM,
    cost: 1000,
    energyConsumption: -50,
    pollutionRadius: 2,
    pollutionCapReduction: 10,
    effects: {},
    color: "#ffffff",
    scale: [0.5, 1, 0.5],
    size: [1, 1]
  },
  [BuildingType.DEPOLLUTION_NODE_LARGE]: {
    type: BuildingType.DEPOLLUTION_NODE_LARGE,
    name: "Purificateur (L)",
    description: "Bloque la pollution étendue.",
    category: BuildingCategory.TERRAFORM,
    cost: 3000,
    energyConsumption: -150,
    pollutionRadius: 4,
    pollutionCapReduction: 30,
    effects: {},
    color: "#ffffff",
    scale: [1, 2, 1],
    size: [2, 2]
  },

  // Default for others
  [BuildingType.FACTORY_ROBOTICS]: { type: BuildingType.FACTORY_ROBOTICS, name: "Usine Robotique", description: "Tech auto.", category: BuildingCategory.INDUSTRY, cost: 4000, energyConsumption: -150, workersRequired: 50, resourceGeneration: 100 * MONEY_MULT, effects: {[StatType.AIR]: -5 * STAT_MULT}, color: "#333333", scale: [1,1,1], size: [2, 2] },
  [BuildingType.RIVER_SEGMENT]: { type: BuildingType.RIVER_SEGMENT, name: "Rivière", description: "Eau courante", category: BuildingCategory.NATURE, cost: 500, energyConsumption: 0, effects: {[StatType.GREENERY]: 8 * STAT_MULT}, color: "#00bfff", scale: [1, 0.05, 1], size: [1, 1]},
  [BuildingType.GARDEN]: { type: BuildingType.GARDEN, name: "Jardin", description: "Petit coin vert", category: BuildingCategory.NATURE, cost: 100, energyConsumption: 0, effects: {[StatType.GREENERY]: 2 * STAT_MULT}, color: "#00ff00", scale: [0.8, 0.1, 0.8], size: [1, 1]},
  [BuildingType.BOTANICAL_GARDEN]: { type: BuildingType.BOTANICAL_GARDEN, name: "Jardin Botanique", description: "Science de la nature", category: BuildingCategory.NATURE, cost: 2000, energyConsumption: -50, effects: {[StatType.GREENERY]: 20 * STAT_MULT}, color: "#00aa00", scale: [1.5, 1, 1.5], size: [2, 2]},
  [BuildingType.OXYGEN_DIFFUSER]: { type: BuildingType.OXYGEN_DIFFUSER, name: "Diffuseur O2", description: "Respiration", category: BuildingCategory.TERRAFORM, cost: 1000, energyConsumption: -30, effects: {[StatType.AIR]: 15 * STAT_MULT}, color: "#e0ffff", scale: [0.8, 1.5, 0.8], size: [1, 1]},
  [BuildingType.HEATER]: { type: BuildingType.HEATER, name: "Chauffage Atm.", description: "Réchauffe", category: BuildingCategory.TERRAFORM, cost: 2500, energyConsumption: -100, effects: {[StatType.EARTH]: 10 * STAT_MULT}, color: "#ff4500", scale: [1, 2, 1], size: [2, 2]},
  [BuildingType.COOLER]: { type: BuildingType.COOLER, name: "Refroidisseur", description: "Refroidit", category: BuildingCategory.TERRAFORM, cost: 2500, energyConsumption: -100, effects: {[StatType.WIND]: 10 * STAT_MULT}, color: "#00ffff", scale: [1, 2, 1], size: [2, 2]},
  [BuildingType.UNDERGROUND_BUNKER]: { type: BuildingType.UNDERGROUND_BUNKER, name: "Bunker", description: "Survie", category: BuildingCategory.LIVING, cost: 1000, energyConsumption: -20, workersProvided: 10, waterConsumption: 2, effects: {}, color: "#555555", scale: [1, 0.2, 1], size: [1, 1]},
  [BuildingType.DOME_CITY]: { type: BuildingType.DOME_CITY, name: "Ville sous Dôme", description: "Protection totale.", category: BuildingCategory.LIVING, cost: 20000, energyConsumption: -1000, workersProvided: 500, waterConsumption: 100, waterStorage: 100, effects: {[StatType.AIR]: 10 * STAT_MULT}, color: "#ffffff", scale: [3, 2, 3], size: [3, 3]},
  [BuildingType.HOTEL]: { type: BuildingType.HOTEL, name: "Hôtel", description: "Tourisme", category: BuildingCategory.LIVING, cost: 3000, energyConsumption: -80, workersProvided: 40, waterConsumption: 15, resourceGeneration: 100 * MONEY_MULT, effects: {}, color: "#ff69b4", scale: [1.5, 3, 1.5], size: [2, 2]},
  [BuildingType.UNIVERSITY]: { type: BuildingType.UNIVERSITY, name: "Université", description: "Savoir", category: BuildingCategory.CIVIC, cost: 8000, energyConsumption: -200, workersRequired: 100, effects: {[StatType.AIR]: 5 * STAT_MULT}, color: "#800080", scale: [2, 1.5, 2], size: [2, 2]},
  [BuildingType.SCHOOL]: { type: BuildingType.SCHOOL, name: "École", description: "Éducation", category: BuildingCategory.CIVIC, cost: 1000, energyConsumption: -20, workersRequired: 20, effects: {}, color: "#ffa500", scale: [1, 0.8, 1], size: [2, 2]},
  [BuildingType.ORBITAL_DOCK]: { type: BuildingType.ORBITAL_DOCK, name: "Quai Orbital", description: "Commerce spatial.", category: BuildingCategory.INDUSTRY, cost: 15000, energyConsumption: -500, workersRequired: 200, resourceGeneration: 400 * MONEY_MULT, effects: {[StatType.AIR]: -10 * STAT_MULT}, color: "#aaaaaa", scale: [2, 4, 2], size: [3, 3]},
  [BuildingType.MINE_TITANIUM]: { type: BuildingType.MINE_TITANIUM, name: "Mine Titane", description: "Métal résistant", category: BuildingCategory.INDUSTRY, cost: 2000, energyConsumption: -60, workersRequired: 40, resourceGeneration: 45 * MONEY_MULT, effects: {[StatType.EARTH]: -4 * STAT_MULT}, color: "#777777", scale: [1.2, 0.7, 1.2], size: [1, 1]},
};

export const INITIAL_MONEY = 5000;